## Libraries

In [11]:
import numpy as np

## Sample Data

In [21]:
# Each row = [hours studied, hours slept]
X = np.array([
    [2, 9],
    [1, 5],
    [3, 6]
])

# Labels: 1 = pass, 0 = fail
y = np.array([
    [1],
    [0],
    [1]
])

print(X)

[[2 9]
 [1 5]
 [3 6]]


## Normalize Data

- Neural networks learn better when inputs are between 0 and 1.
- This scales down the values to that range (e.g. 5 becomes 0.5 if max is 10).

X = X / np.amax(X, axis=0)
print(X)

## Initialize Weights Randomly

- Each input feature needs a weight (importance).
- The network "learns" the best weights over time.
- We start with random values.

In [25]:
np.random.seed(42)  # for consistent results
weights = np.random.rand(2, 1)

print(weights)

[[0.37454012]
 [0.95071431]]


## Activation Function

- Without this, the output could be any number (like 14 or -7).
- Sigmoid "squashes" the output between 0 and 1 this is perfect for probabilities
- It's like: "how confident is the model that this person will pass?"

In [27]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

## Forward Pass (Prediction)

This simulates a single layer neural network:

- Multiply inputs by weights (like: 5 hrs * 0.4 + 6 hrs * 0.6)
- Applying sigmoid, e.g., 0.91 -> 91% chance of passing
- Dot products or matrix multiplication in ML are usually computing how strongly inputs activate a neuron.

In [29]:
def predict(X, weights):
    z = np.dot(X, weights)     # linear part: inputs × weights
    output = sigmoid(z)        # apply non-linear activation
    return output

In [31]:
predictions = predict(X, weights)
print(predictions)

[[0.99990909]
 [0.99410719]
 [0.99891805]]


## Loss Function (MSE)

- Measures how bad the model's predictions are.
- Smaller value = better prediction.
- This helps guide the learning process in training.

In [33]:
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

loss = mean_squared_error(y, predictions)
print(f"Loss: {loss}")

Loss: 0.3294167597215201


## Backward Pass & Weight Update

- Right now, the model uses random weights.
- In training, it compares predictions with actual answers and adjusts the weights to get better.
- That process is called backpropagation.

In [35]:
def sigmoid_derivative(x):
    return x * (1 - x)

learning_rate = 0.1

for epoch in range(1000):
    z = np.dot(X, weights)
    output = sigmoid(z)

    error = y - output
    adjustments = error * sigmoid_derivative(output)

    weights += np.dot(X.T, adjustments) * learning_rate

## Output Example:

In [57]:
# Example prediction for one student
student = np.array([5, 6]) / np.amax(X, axis=0)
result = predict(student.reshape(1, -1), weights)
print(result)

[[0.97380948]]
